Update local-cluster-setup-with-polar.md
lightninglabs/docs.lightning.engineering pull request #65
Opened 2021-03-24 02:46 UTC by joelklabo

Update download link for Polar

Pull Request Checklist
- [x] The documents updated are not in the `docs/` directory. These files are
  synced from upstream repositories ([lnd](https://github.com/lightningnetwork/lnd), [lit](https://github.com/lightninglabs/lightning-terminal), [loop](https://github.com/lightninglabs/loop), [pool](https://github.com/lightninglabs/pool) and [faraday](https://github.com/lightninglabs/faraday)), and 
  should be updated in their parent repo.

2021-03-24 11:14 UTC, guggero approved these changes
LGTM, thanks!

2021-03-24 14:39 UTC, jamaljsr requested changes
Good catch. However, the "can be downloaded" link should be pointed to https://lightningpolar.com. Can you update that, this is PR will be all good.

2021-03-24 21:16 UTC, joelklabo commented
No problem, updated @jamaljsr

2021-12-07 15:12 UTC, lightninglabs-deploy commented
@joelklabo, remember to re-request review from reviewers for your latest update

2021-12-07 19:11 UTC, jamaljsr approved these changes

2023-03-01 04:54 UTC, closed without merging